export interface Person {
  id: string
  name: string
  jobTitle: string
  company: string
  owner: string
  dealName: string
  dealId: string
  phone: string
  email: string
  location: string
  segment: string
  // Optional freeform note stored for this contact (kept in localStorage at runtime)
  note?: string
  sequenceEnrollment?: {
    sequenceName: string
    currentStep: string
    stepNumber: number
    totalSteps: number
    status: 'active' | 'completed' | 'paused'
  }
}

// Shared people dataset so multiple views (people, companies, pipelines) can reuse it
export const peopleData: Person[] = [
  {
    id: '1',
    name: 'James Robertson',
    jobTitle: 'Head of Infrastructure Projects',
    company: 'Balfour Beatty',
    owner: 'Emma Thompson',
    dealName: 'HS2 Rail Infrastructure Package',
    dealId: 'deal-001',
    phone: '+44 20 7216 6800',
    email: 'james.robertson@balfourbeatty.com',
    location: 'London, UK',
    segment: 'Major contractor',
    sequenceEnrollment: {
      sequenceName: 'Major Projects Outreach',
      currentStep: 'Initial meeting scheduled',
      stepNumber: 2,
      totalSteps: 5,
      status: 'active',
    },
  },
  {
    id: '2',
    name: 'Sarah Mitchell',
    jobTitle: 'Commercial Director',
    company: 'Kier Group',
    owner: 'David Clarke',
    dealName: 'M25 Highways Upgrade',
    dealId: 'deal-002',
    phone: '+44 1923 423 840',
    email: 'sarah.mitchell@kier.co.uk',
    location: 'Hertfordshire, UK',
    segment: 'Major contractor',
    sequenceEnrollment: {
      sequenceName: 'Standard Outreach',
      currentStep: 'Email sent - waiting for response',
      stepNumber: 2,
      totalSteps: 5,
      status: 'active',
    },
  },
  {
    id: '3',
    name: 'Thomas Harrison',
    jobTitle: 'Head of Procurement',
    company: 'Morgan Sindall Group',
    owner: 'Emma Thompson',
    dealName: 'Liverpool Regeneration Project',
    dealId: 'deal-003',
    phone: '+44 20 7307 9200',
    email: 'thomas.harrison@morgansindall.com',
    location: 'London, UK',
    segment: 'Major contractor',
    sequenceEnrollment: {
      sequenceName: 'Procurement Outreach',
      currentStep: 'Follow-up call completed',
      stepNumber: 3,
      totalSteps: 5,
      status: 'active',
    },
  },
  {
    id: '4',
    name: 'Emily Davies',
    jobTitle: 'Project Director - Buildings',
    company: 'Galliford Try',
    owner: 'David Clarke',
    dealName: 'Healthcare Facilities Programme',
    dealId: 'deal-004',
    phone: '+44 1895 855 001',
    email: 'emily.davies@gallifordtry.co.uk',
    location: 'Uxbridge, UK',
    segment: 'Major contractor',
    sequenceEnrollment: {
      sequenceName: 'Healthcare Sector Focus',
      currentStep: 'Proposal submitted',
      stepNumber: 4,
      totalSteps: 5,
      status: 'active',
    },
  },
  {
    id: '5',
    name: "Michael O'Connor",
    jobTitle: 'Energy Sector Lead',
    company: 'Costain Group',
    owner: 'Emma Thompson',
    dealName: 'Thames Water Infrastructure',
    dealId: 'deal-005',
    phone: '+44 20 7940 8400',
    email: 'michael.oconnor@costain.com',
    location: 'London, UK',
    segment: 'Major contractor',
    sequenceEnrollment: {
      sequenceName: 'Energy & Water Focus',
      currentStep: 'Contract negotiation',
      stepNumber: 5,
      totalSteps: 5,
      status: 'completed',
    },
  },
  {
    id: '6',
    name: 'Sophie Turner',
    jobTitle: 'Director of Strategic Projects',
    company: "Laing O'Rourke",
    owner: 'David Clarke',
    dealName: 'London Gateway Port Expansion',
    dealId: 'deal-006',
    phone: '+44 1322 296 200',
    email: 'sophie.turner@laingorourke.com',
    location: 'Dartford, UK',
    segment: 'Major contractor',
    sequenceEnrollment: {
      sequenceName: 'Major Projects Outreach',
      currentStep: 'Initial contact made',
      stepNumber: 1,
      totalSteps: 5,
      status: 'active',
    },
  },
  {
    id: '7',
    name: 'Andrew Phillips',
    jobTitle: 'Sustainability & Green Building Lead',
    company: 'Skanska UK',
    owner: 'Emma Thompson',
    dealName: 'Net Zero Office Development',
    dealId: 'deal-007',
    phone: '+44 1923 423 000',
    email: 'andrew.phillips@skanska.co.uk',
    location: 'Hertfordshire, UK',
    segment: 'Major contractor',
  },
  {
    id: '8',
    name: 'Rachel Williams',
    jobTitle: 'Head of Facilities Management',
    company: 'BAM UK & Ireland',
    owner: 'David Clarke',
    dealName: 'University Campus FM Contract',
    dealId: 'deal-008',
    phone: '+44 1442 238 300',
    email: 'rachel.williams@bam.com',
    location: 'Hemel Hempstead, UK',
    segment: 'Major contractor',
    sequenceEnrollment: {
      sequenceName: 'Facilities Management Focus',
      currentStep: 'Site visit arranged',
      stepNumber: 3,
      totalSteps: 5,
      status: 'active',
    },
  },
  {
    id: '9',
    name: 'Oliver Bennett',
    jobTitle: 'Land Director',
    company: 'Barratt Redrow',
    owner: 'Emma Thompson',
    dealName: 'Cambridge New Town Development',
    dealId: 'deal-009',
    phone: '+44 1530 278 278',
    email: 'oliver.bennett@barrattredrow.co.uk',
    location: 'Coalville, UK',
    segment: 'Housebuilder',
    sequenceEnrollment: {
      sequenceName: 'Housing Development Outreach',
      currentStep: 'Planning approval support',
      stepNumber: 4,
      totalSteps: 5,
      status: 'active',
    },
  },
  {
    id: '10',
    name: 'Charlotte Brown',
    jobTitle: 'Partnerships Director',
    company: 'Persimmon plc',
    owner: 'David Clarke',
    dealName: 'Affordable Housing Partnership',
    dealId: 'deal-010',
    phone: '+44 1904 642 199',
    email: 'charlotte.brown@persimmonhomes.com',
    location: 'York, UK',
    segment: 'Housebuilder',
    sequenceEnrollment: {
      sequenceName: 'Partnership Outreach',
      currentStep: 'Partnership agreement drafted',
      stepNumber: 4,
      totalSteps: 5,
      status: 'active',
    },
  },
  {
    id: '11',
    name: 'Daniel Wright',
    jobTitle: 'Regional Managing Director',
    company: 'Taylor Wimpey',
    owner: 'Emma Thompson',
    dealName: 'Thames Valley Residential Scheme',
    dealId: 'deal-011',
    phone: '+44 1494 885 555',
    email: 'daniel.wright@taylorwimpey.com',
    location: 'High Wycombe, UK',
    segment: 'Housebuilder',
  },
  {
    id: '12',
    name: 'Lucy Anderson',
    jobTitle: 'Technical Director',
    company: 'Bellway plc',
    owner: 'David Clarke',
    dealName: 'North East Housing Development',
    dealId: 'deal-012',
    phone: '+44 191 217 0717',
    email: 'lucy.anderson@bellway.co.uk',
    location: 'Newcastle upon Tyne, UK',
    segment: 'Housebuilder',
    sequenceEnrollment: {
      sequenceName: 'Technical Specification Focus',
      currentStep: 'Technical review meeting',
      stepNumber: 2,
      totalSteps: 5,
      status: 'active',
    },
  },
  {
    id: '13',
    name: 'Henry Clarke',
    jobTitle: 'Development Director',
    company: 'Berkeley Group Holdings',
    owner: 'Emma Thompson',
    dealName: 'Canary Wharf Mixed-Use Tower',
    dealId: 'deal-013',
    phone: '+44 1932 868 555',
    email: 'henry.clarke@berkeleygroup.co.uk',
    location: 'Cobham, UK',
    segment: 'Housebuilder',
    sequenceEnrollment: {
      sequenceName: 'Urban Development Outreach',
      currentStep: 'Design consultation phase',
      stepNumber: 3,
      totalSteps: 5,
      status: 'active',
    },
  },
  {
    id: '14',
    name: 'Rebecca Thompson',
    jobTitle: 'Head of Affordable Housing',
    company: 'Vistry Group',
    owner: 'David Clarke',
    dealName: 'Social Housing Initiative',
    dealId: 'deal-014',
    phone: '+44 1923 896 555',
    email: 'rebecca.thompson@vistrygroup.co.uk',
    location: 'Watford, UK',
    segment: 'Housebuilder',
  },
  {
    id: '15',
    name: 'George Patterson',
    jobTitle: 'National Account Manager',
    company: 'Travis Perkins plc',
    owner: 'Emma Thompson',
    dealName: 'National Supply Partnership',
    dealId: 'deal-015',
    phone: '+44 1604 683 100',
    email: 'george.patterson@travisperkins.co.uk',
    location: 'Northampton, UK',
    segment: 'Merchant / distributor',
    sequenceEnrollment: {
      sequenceName: 'Supply Chain Outreach',
      currentStep: 'Pricing proposal submitted',
      stepNumber: 4,
      totalSteps: 5,
      status: 'active',
    },
  },
  {
    id: '16',
    name: 'Victoria Hughes',
    jobTitle: 'Branch Network Director',
    company: 'Jewson (Stark Group)',
    owner: 'David Clarke',
    dealName: 'Regional Distribution Agreement',
    dealId: 'deal-016',
    phone: '+44 1473 237 500',
    email: 'victoria.hughes@jewson.co.uk',
    location: 'Ipswich, UK',
    segment: 'Merchant / distributor',
    sequenceEnrollment: {
      sequenceName: 'Distribution Network Focus',
      currentStep: 'Initial meeting completed',
      stepNumber: 2,
      totalSteps: 5,
      status: 'active',
    },
  },
  {
    id: '17',
    name: 'Alexander Scott',
    jobTitle: 'Chief Engineer - Rail',
    company: 'Balfour Beatty',
    owner: 'Emma Thompson',
    dealName: 'Crossrail 2 Feasibility',
    dealId: 'deal-017',
    phone: '+44 20 7216 6820',
    email: 'alexander.scott@balfourbeatty.com',
    location: 'London, UK',
    segment: 'Major contractor',
  },
  {
    id: '18',
    name: 'Grace Robinson',
    jobTitle: 'Operations Director',
    company: 'Morgan Sindall Group',
    owner: 'David Clarke',
    dealName: 'Birmingham City Centre Fit-Out',
    dealId: 'deal-018',
    phone: '+44 20 7307 9250',
    email: 'grace.robinson@morgansindall.com',
    location: 'London, UK',
    segment: 'Major contractor',
    sequenceEnrollment: {
      sequenceName: 'Fit-Out Specialists',
      currentStep: 'Detailed quotation phase',
      stepNumber: 3,
      totalSteps: 5,
      status: 'active',
    },
  },
]


